import Navbar from "@/components/Navbar";
import "./globals.css";

export const metadata = {
  title: "Paw Friends",
  description: "Generated by create next app",
  viewport: {
    width: "device-width",
    initialScale: 1,
    maximumScale: 1,
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main className="px-[20px] lg:px-[150px]">{children}</main>
      </body>
    </html>
  );
}
